### ISSUE TITLE
display value format method? 

### ISSUE THREAD

**Issue by kulabros** [bymi15/react-edit-text#15]
Hi there, thank you for this awesome component! I'm thinking of how to easily format displayed value. There's react component's state as a value property, of 0-1 value, corresponding percents value. I'm using range slider, with min 0 max 1, step 0.01, that set's me the value I need perfectly, value is in 0.33 format on input and output too, so that's why I have this value in the state in this format. Than I just do value*100 to get percents format.. I need to allow to the user, to manually edit the value, that's why I choose this react-edit-text component. To avoid float dividing, I'm thinking of how I could format the displayed value.. I was thinking of combining react-edit-text with react-number-format, maybe of extending the original class with some extra value in the state that is formatted, or just adding extra function to the component, that would allow me to define format method, to the displayed value (savedText). Are there some further use cases, about how to handle value formatting on output? Thank you very much for any help. Again - I have state value, for example happinessToday = 0.67, this value is used to ne editable by range-slider from bootstrap, and the value is rendered in html to the user too. But, internally I need to have this format, on output I need to have 0-100% format, that can be edited manually using react-edit-text. And the entered value can be more precise, then the range slider, so I could write 67.45, the value would be displayed, but internal state property would be 0.6745.... Any thoughts how to get this kind of value formatting? Thanks for ANY tips how to move on with this. The callback from editText and range-slider are handling the same property, and I want to avoid /100 floating.... Maybe I'm missing something out of the box of this component, sure you can close this issue if it suppose to be OT. Have a nice day! M.

**Comment by bymi15** [comment]
I've just released a new `formatDisplayValue` prop where you can pass in a function that formats the value to display.
Closing this issue as this should resolve your use case.

**Comment by kulabros** [comment]
> I've just released a new `formatDisplayValue` prop where you can pass in a function that formats the value to display. Closing this issue as this should resolve your use case.

WOW! :) Amazing! I'm going ahead it, thank you very very much!!! :)
