### ISSUE TITLE
autofocus on render

### ISSUE THREAD

**Issue by inmortalkaktus** [bymi15/react-edit-text#21]
I am using react-edit-text for a flashcard application. I have a button that is used to create new cards, and when I press it, a new card with an EditText component is mapped in the DOM.

I have implemented a function through useRef that once the card appears, the "EditText" component is automatically clicked so as not to have to click on the text again to change it.

It would be great if this was implemented.

**Comment by bymi15** [comment]
Hi,
I can consider adding a prop that sets the initial state of the component (either in edit mode or display mode).
For example, the following would resolve your use case:
```javascript
<EditText initialState="edit"/>
```

Please let me know whether you think this would work for you.

**Comment by inmortalkaktus** [comment]
Well, I already had a workaround at the moment of creating the issue, but with that, it would be much much easier.
