### ISSUE TITLE
Return the object in the props

### ISSUE THREAD

**Issue by inmortalkaktus** [bymi15/react-edit-text#22]
In props like onChange, the event should be received instead of the value directly. Thus, when calling some function from the prop, custom props can be accessed as "name" of the EditText component.

**Comment by bymi15** [comment]
Hi,
It would be helpful if you could provide some examples of how you would use the `onChange` prop in the way you described it.
I'm not sure whether this would be a bug though.

**Comment by inmortalkaktus** [comment]
Right now, the return statement of the onChange prop is the value of the input. It would me more dynamic if you return the whole input object so that you don't have to search again the object if you want to modify, delete or get some other value.
