### ISSUE TITLE
EditText inline becomes a block while editing

### ISSUE THREAD

**Issue by giohappy** [bymi15/react-edit-text#29]
I've tried using the `inline` prop to make the `EditText` render inline. It works until you don't edit it. Once it's clicked it gets assigned the default `_1EEDX` class, which has `display: block`.

`<div><EditText value={name} inline />[{id}]</div>`

This:
![image](https://user-images.githubusercontent.com/571129/170495747-8e8e4055-7427-4920-8ba9-17a58a56c9ca.png)

becomes:
![image](https://user-images.githubusercontent.com/571129/170495998-e26b2ea3-0365-47ab-8f89-58044bac5088.png)

How should I style the component to show inline while editing?

**Comment by bymi15** [comment]
Hi @giohappy,
Thanks for raising this. There is currently a bug with the props not being properly passed to the display component.
This will be fixed soon!

**Comment by giohappy** [comment]
thanks for the feedback @bymi15. Do you know when the fix will be available?
