### ISSUE TITLE
@types/react-edit-text has incorrect type for EditText onChange

### ISSUE THREAD

**Issue by walkingbrad** [bymi15/react-edit-text#40]
**Describe the bug**
The latest version of `@types/react-edit-text` declares `EditText`'s `onChange` prop as:
```
/**
 * onChange is called when the input value changes and
 * returns a string which corresponds to the new input value
 */
onChange?: (value: string) => void;
```

But it seems the actual javascript code is passing an `object` instead, presumably the `Event` object from looking at the code in this repo.

**To Reproduce**
1. Create an `EditText` component and pass an `onChange` prop with a log that prints if the passed value is a string or an object
2. Run it in a browser
3. Type something in the `EditText` field
4. Check the log to see what type is passed

**Expected behavior**
The `onChange` prop is passed a `string`, since `@types/react-edit-text` indicates such.

It's fine that some object is passed, but the type definition just needs to be updated accordingly so we can get type safety in Typescript.

**Comment by bymi15** [comment]
Hey, thanks for raising this!
I'll be raising an update request for the v5 breaking changes soon.
The repo that manages the types is: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by bymi15** [comment]
The new version has been released, you can simply update your `@types/react-edit-text` package to v5.0.0 and it should work.
https://www.npmjs.com/package/@types/react-edit-text

**Comment by RKS24** [comment]
@bymi15 on change event is not getting fired
