### ISSUE TITLE
onEditMode type error

### ISSUE THREAD

**Issue by rfdearborn** [bymi15/react-edit-text#41]
**Describe the bug**

Using the `onEditMode` prop in (a typescripted) `EditText` returns `Property 'onEditMode' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<EditText> & Readonly<EditTextProps>'.`. I think this is because it's not defined [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-edit-text/index.d.ts)? 

**Environment**
I'm on react-edit-text 5.0.2 and @types/react-edit-text 5.0.0

Awesome package btw!

**Comment by bymi15** [comment]
Hi, thanks for raising this!
Can't believe this was completely missed out during the past few DefinitelyTyped updates.. as that prop was added back in [v4.2.0](https://github.com/bymi15/react-edit-text/releases/tag/v4.2.0).
Anyways, i've fixed this and raised a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61297

**Comment by bymi15** [comment]
The fix has been released.
Please update https://www.npmjs.com/package/@types/react-edit-text to v5.0.1
