### ISSUE TITLE
Edit SVG icon in the documentation website is out of proportion on Firefox browser 

### ISSUE THREAD

**Issue by 8mn** [bymi15/react-edit-text#43]
**Describe the bug**
Due to no fixed width or height, the edit SVG icon (which is pencil) is disproportionately large on Firefox.

**To Reproduce**
1. Visit [https://brianmin.com/react-edit-text/](https://brianmin.com/react-edit-text/) on Firefox.

**Expected behavior**
on Chrome

![image](https://user-images.githubusercontent.com/64839201/184547767-bba1a5bc-ccb4-47da-be35-4363e48a6a20.png)

**Screenshots**
on Firefox

![image](https://user-images.githubusercontent.com/64839201/184547654-a53e6bb1-f7e8-4e68-af8b-9e36707520a5.png)

**Environment**
 - OS: Windows
 - Browser: Firefox
 - Version: 103.0.2

**Additional context**
None

**Comment by bymi15** [comment]
Thanks for raising this, i'll be fixing it shortly 😸
