### ISSUE TITLE
Customize button and input components / styles

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [bymi15/react-edit-text#46]
**Is your feature request related to a problem? Please describe.**
I am using Ant Design and I want `react-edit-text` to use ant design input / button / text. Here is a demo: https://codesandbox.io/s/antd-editable-tabs-5bl1ty?file=/src/App.tsx. In the demo you can toggle using edit text to see how the tabs get very tall and look wierd.

**Describe the solution you'd like**
Props like this:
```jsx
import { EditText } from 'react-edit-text'
import { Button, Input } from 'antd'

<EditText
  renderText={input => <Button type='text' {...input} />}
  renderInput={input => <Input {...input} />}
/>
```

**Describe alternatives you've considered**
Make my own component which uses Ant Design components.

**Additional context**
Demo is based off of https://ant.design/components/tabs/#components-tabs-demo-editable-card, but I also want to rename tabs.

**Comment by bymi15** [comment]
Hey @ChocolateLoverRaj 
You can achieve that by making use of the `className` prop or `style` prop and setting a maxWidth and maxHeight to prevent the input from exceeding the specified width/height.
For example:
```js
<EditText
    style={{ maxWidth: 63, maxHeight: 32 }}
    value={name}
    onChange={({ target: { value } }) => {
      setTabs((tabs) => [
        ...tabs.slice(0, index),
        value,
        ...tabs.slice(index + 1)
      ]);
    }}
/>
```
This works from your example.
https://codesandbox.io/embed/antd-editable-tabs-forked-7el90n?fontsize=14&hidenavigation=1&theme=dark

**Comment by ChocolateLoverRaj** [comment]
It would still be more convenient if I could customize the component itself. 

Also the example you created had still taller tabs than normal (i checked on mobile, idk if it's different on bigger screen).
