### ISSUE TITLE
How to put the input in edit mode without clicking on the input or the edit button

### ISSUE THREAD

**Issue by abolfazl30not30** [bymi15/react-edit-text#48]
There is a button on the page that the user clicks to create a new edit text element
I want a new edit text element to be created when the user clicks on the button and the edit text element will be  on edit mode automatically

**Comment by bymi15** [comment]
Hi,
I don't quite understand what you are asking for.
It would be helpful to have some screenshots to support your description.
Otherwise, please feel free to fork the repo, raise a PR and i'll be happy to review.
