### ISSUE TITLE
Comparison with the previous value

### ISSUE THREAD

**Issue by knoxgon** [bymi15/react-edit-text#5]
I'm aware that the library is fairly new but it would be sweet if within `onSave({ name, value }: onSaveProps)`, you could also compare with the previous value before the persistence process.

`onSave({ name, value, prevValue }: onSaveProps)`

This additional property would definitely cut the problem for the end-user to create additional states to keep an eye on the previous value.

**Comment by bymi15** [comment]
Hi knoxgon,

That sounds like a great idea!
I will work on this later when I have time.
But if you think you are able to implement this, feel free to fork this repo, implement the feature, and make a pull request.

Thanks,
Brian.

**Comment by bymi15** [comment]
Fixed in commit 3057b92078bc95e4cb3a6ddb654c0611df2e3f67.
Released v4.0.0.
