### ISSUE TITLE
Not showing text when passed in as props variable

### ISSUE THREAD

**Issue by callum-osborne** [bymi15/react-edit-text#7]
Really cool tool I'm just having trouble getting it working with variables that were declared outside the component.
I've got this:

`<EditTextarea className="text-secondary pb-3" defaultValue={this.props.data_in.class_description} rows={4} />`

The text is not showing in the text area either when not editing or editing but if I was to replace the variable with another string declared in this class it would work fine.

I have tried setting it to a variable in the class and then using that but can't seem to get it working, is this something that should be possible?

To elaborate:

If I was to make changes and save them then the text would show, but if I refreshed it would disappear.
I tried to copy the string into another variable in the class, changed the text of the string and copied the variable into a state but with no success.

**Comment by bymi15** [comment]
Have you try using the `value` prop and `onChange` prop instead of `defaultValue`?
You can find the full documentation on: [https://bymi15.github.io/react-edit-text/](https://bymi15.github.io/react-edit-text/)

For example:
```
const [textarea, setTextarea] = React.useState(
  'Initial value for text area'
);

const handleSave = ({name, value}) => {
  alert(name + ' component saved as: ' + value);
}

<EditTextarea
  name='textarea'
  value={textarea}
  onChange={setTextarea}
  onSave={handleSave}
/>
```

**Comment by callum-osborne** [comment]
I have just tried that, code below, I seem to be getting the same problem. It does not show the text when it is passed in from the props data.

I added a console log to make sure the string was stored in the variable. Does it work on your system?

`const App = (props) => {

  const [textarea, setTextarea] = React.useState(

    props.data_in.class_description

  );

  const handleSave = ({name, value}) => {

    console.log(props.data_in.class_description)

      // alert(name + ' saved as: ' + value);

  }

  return (
      <Card small className="h-100">

      <CardHeader className="border-bottom">
        <h6 className="m-0">About</h6>          
      </CardHeader>

      <CardBody className="d-flex flex-column">

      {/* <EditText className="text-secondary pb-3" defaultValue={this.props.data_in.class_description} rows={4} /> */}
        
      <EditTextarea
        name='textarea'
        value={textarea}
        onChange={setTextarea}
        onSave={handleSave}
      />

      </CardBody>

    </Card>
  )
}`

**Comment by bymi15** [comment]
Yes I have tested the code and it works on my system.
Are you sure you are passing the correct props to your `App` component?
I.e. `<App data_in = {some_obj}/>` where you define for example: `const some_obj = { class_description: "some_text" }`

**Comment by callum-osborne** [comment]
Thanks for the help, I found the issue to be due to the late update of the variable passed into the component. As if I had replaced the variable with a static variable it would work.

I fixed it using a `componentWillReceiveProps` function within the component to update the variable when a new one is passed in, I have attached my working code in case someone else runs into this problem.

```
class About extends React.Component {
  constructor(props) {
    super(props);

    this.canvasRef = React.createRef();    

    this.state = {
      class_description: this.props.data_in.class_description
    }
  }

  componentWillReceiveProps(nextprops) {
    this.setState({ class_description: nextprops.data_in.class_description });  
  }

  render() {
    
    const handleSave = ({name, value}) => {
      this.setState({ class_description: value });       
    }
    

    const { data_in } = this.props;
    return (
      ...

          <EditTextarea
            className="text-secondary pb-2"
            name='textarea'
            value={this.state.class_description}
            onChange={(value) => this.setState({ class_description: value})}
            onSave={handleSave}
          />

```
