### ISSUE TITLE
display value?

### ISSUE THREAD

**Issue by chrisschaub** [bymi15/react-edit-text#8]
Would there be a way to "display" parsed text, but when edit is clicked, just edit raw value? Thinking of parsing text for urls on display.

**Comment by bymi15** [comment]
Hi thank you for your feedback.
I am not sure if I understood correctly, but wouldn't that cause a conflict?
If I were to click on the component, would it open edit mode or would it navigate me to the URL?

**Comment by fxgit** [comment]
It would be great to be able to give a function to format the value. for example in edit mode an input with the number 5 is shown but when not edited this function formats the value to the text "5 inches"
